### ISSUE TITLE
Movement 

### ISSUE THREAD

**Issue by Micrified** [Micrified/LocationRecognition#8]
Last year I used a built-in step-counter to count steps, and then had a fixed variable for the distance covered. It would be better to implement this as a setting so that I can adjust the distance per step or that it can be updated in real-time. 

Stride length estimation paper: Maybe take a glance at the abstract

**Comment by HeatPhoenix** [comment]
Only thing that's left is the option to ask the user to walk x meters and getting the stride length from that.
